services:
    web-nginx:
        image: nginx:latest
        container_name: nginx-mcit-cont
        links:
            - "php8-fpm:php"
        ports:
            - 10080:80
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "../web/:/var/www/html/"
    php8-fpm:
        build: ./php
        image: php8-fpm:mcit-ken
        container_name: php8-mcit-cont
        ports:
            - 9000:9000
        volumes:
            - "../web/:/var/www/html/"
